/**
 * This class is generated by jOOQ
 */
package jooq;


import jooq.tables.Book;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Lab08 extends SchemaImpl {

	private static final long serialVersionUID = 2055164008;

	/**
	 * The reference instance of <code>lab08</code>
	 */
	public static final Lab08 Lab08 = new Lab08();

	/**
	 * No further instances allowed
	 */
	private Lab08() {
		super("lab08");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Book.BOOK);
	}
}
