/**
 * This class is generated by jOOQ
 */
package jooq;


import jooq.tables.Book;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in lab08
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table lab08.book
	 */
	public static final Book BOOK = jooq.tables.Book.BOOK;
}
